# Generated by Django 4.0.6 on 2022-08-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('weight', models.FloatField()),
                ('delta', models.FloatField()),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
